on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
    - name: connect and pull
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: | 
          cd product_landing_page
          git pull origin main
          fuser -n tcp -k 3001
          python3 -c "import subprocess; subprocess.Popen(['python3', '-m', 'http.server', '3001']); exit()" &
          exit 0
