on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
    - name: connect and pull
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: | 
          cd product_landing_page
          git checkout main
          git pull origin main
        
    - name: run server
      run: |
        freeport 8080
        yes
        python3
        import subprocess
        subprocess.Popen(["python", "-m", "http.server", "8080"])
        exit()
    
