on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
    - name: connect and pull
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: | 
          cd product_landing_page
          git pull origin main
        
    - name: clear port 3001
      run: (fuser -n tcp -k 3001) || true
      
    - name: run server
      run: RUNNER_TRACKING_ID="" && (python3 -c "import subprocess; import time; subprocess.Popen(['python3', '-m', 'http.server', '3001']); time.sleep(5); exit()")

